

[/Script/EngineSettings.GameMapsSettings]
;GameDefaultMap=/Game/Maps/Main.Main
;EditorStartupMap=/Game/Maps/Main.Main
GameInstanceClass=/Script/Abrams.AbramsGameInstance
;GameInstanceClass=/Game/ModKit/ModGameInstance_BP
GlobalDefaultGameMode=/Script/Abrams.AbramsGameModeBase
bUseSplitscreen=False

[/Script/UnrealEd.CookerSettings]
cook.AllowCookedDataInEditorBuilds=True

[ConsoleVariables]
s.AllowUnversionedContentInEditor=1
CanUseUnversionedPropertySerialization=True

[/Script/UnrealEd.EditorLoadingSavingSettings]
bLoadDefaultLevelAtStartup=False

[Core.Log]
LogShaders=Fatal

[/Script/Engine.Engine]
bUseFixedFrameRate=True
CameraTranslationThreshold=1
CameraRotationThreshold=1
FixedFrameRate=60.000000

[Animation.DefaultObjectSettings]
BoneCompressionSettings=/Game/Editor/ACLPlugin/ACLAnimBoneCompressionSettings
CurveCompressionSettings=/Game/Editor/ACLPlugin/ACLAnimCurveCompressionSettings

[/Script/Engine.StreamingSettings]
s.AsyncLoadingThreadEnabled=True
