#pragma once
#include "CoreMinimal.h"
#include "EGameItemUnlockConditionsType.generated.h"

UENUM(BlueprintType)
enum class EGameItemUnlockConditionsType : uint8 {
    None,
    Default,
    StoryCharaRelateThreshold,
    StoryMissionClearRank,
    StoryAllMissionClearRank,
    StoryChapterAllMissionClearRank,
    StoryAllChapterClear,
    StoryTotalClearMissionTask,
    StoryAllMissionTaskClear,
    StoryReleaseAllCorrelationDiagramCharacter,
    PvERiskValueThreshold,
    PvEModePlayCount,
    PvEModeClearCount,
    PvEModeClearRankCount,
    PvENormalModeClearCount,
    PvESurvivalModeClearCount,
    PvETaskClearCount,
    PvEBindingVowsEquipmentCount,
    PvEGrowthCharaLevelThreshold,
    PvEGrowthAnyCharaLevelThreshold,
    PvETotalGrowthCharaLevelThreshold,
    PvEHealPointUseCount,
    PvPBattleCount,
    PvPBattleWinCount,
    PvPBattleWinResultRankThreshold,
    PvPRankMatchWinCount,
    PvPRankMatchWinningStreakCount,
    PvPRankPointMax,
    UseCharacterCount,
    StageSelectCount,
    DashCount,
    JustGuardCount,
    GuardBreakCount,
    CursedEnergyLevelupCount,
    CursedEnergyAttackLevelMaxCount,
    ShortRangeAttackCount,
    LongRangeAttackCount,
    DebuffCount,
    SuperCursedEnergyAttackCount,
    DomainExpansionCount,
    SpecialTagComboCount,
    FriendBattleCount,
    TotalMoney,
    TotalCostume,
    TotalTitle,
    TotalCursedTools,
    UseMultiCharacterCount,
    UseCharacterGroupCount,
    UsePvPCharacterGroupCount,
    PvEModeClearRiskValue,
    ArcadeModeClear,
    ArcadeModeClearCount,
    ArcadeModeCharacterClear,
    ArcadeModeCharacterNoContinueClear,
    ArcadeModeCharacterNoContinueClearHard,
    PvEExtraMissionCount,
    PvEExtraMissionClearCount,
    StoryMissionTaskClear,
    TotalEquipment,
    UseKyotoStudentsCount,
    Invalid = 255,
};

