#pragma once
#include "CoreMinimal.h"
#include "EGameBuffDebuff.generated.h"

UENUM(BlueprintType)
enum class EGameBuffDebuff : uint8 {
    None,
    CP_010_Passive,
    Coercion,
    Hairpin_1,
    Hairpin_2,
    Hairpin_3,
    Resonance_1,
    Resonance_2,
    Resonance_3,
    CP_040_Passive,
    CP_051_Passive,
    CP_060_Passive,
    CP_081_Passive,
    CP_090_Passive,
    CP_100_Passive,
    CP_110_CursedEnergyAttack2,
    CP_110_Passive,
    DomainExpansion_CP_130,
    DomainExpansion_CP_130_Enemy,
    DomainExpansion_CP_140,
    DomainExpansion_CP_140_Enemy,
    CP_140_Passive,
    CP_150_Passive,
    RotTechnique,
    Decay_1,
    Decay_2,
    Decay_3,
    CP_160_Passive,
    MoveSlow,
    MoveSlowItem,
    HitPointRecoverWithTimeItem,
    CursedEnergyRecoverSlow,
    CursedEnergyExpIncrease,
    CursedEnergyExpIncreaseItem,
    CursedEnergyExpDecreaseItem,
    DashDisabledItem,
    DashGaugeUnlimitedItem,
    DashGaugeRecoverIncreaseItem,
    DashGaugeRecoverDecreaseItem,
    DashGaugeNotRecoverItem,
    SendDamageIncreaseItem,
    SendDamageDecreaseItem,
    ReceiveDamageDecreaseItem,
    ReceiveDamageWithTimeItem,
    LinkComboCursedEnergyExpIncreaseItem,
    SuperArmorItem,
    CursedEnergyRecoverIncrease,
    CP_170_Passive,
    CP_180_Passive,
    CP_200_Passive,
    CP_190_Passive,
    CP_210_Passive,
    CP_220_Passive_Weak,
    CP_220_Passive_Strong,
    CP_230_CursedEnergyAttack1,
    CP_240_Passive,
    CP_250_Passive,
    CP_260_Passive,
    CN_230_Passive,
    CN_250_Passive,
    IceFormation_Begin,
    IceFormation_Damage,
    IceFormation_Debuff,
    Adapt_CursedEnergyAttack_1,
    Adapt_CursedEnergyAttack_2,
    Adapt_ExtraAttack,
    Adapt_TagCombo,
    Invalid = 255,
};

