#pragma once
#include "CoreMinimal.h"
#include "EGameRankingRecord.generated.h"

UENUM(BlueprintType)
enum class EGameRankingRecord : uint8 {
    None,
    SendDamage,
    ReceiveDamage,
    AceAttacker,
    FirstDown,
    CursedEnergyCharge,
    CursedEnergySense,
    Jammer,
    TurboDash,
    JustGuard,
    DomainExpansionMania,
    GuardBreak,
    OverwhelmingBattle,
    Finisher,
    Runner,
    SpecialTagCombo,
    SuperCursedEnergyAttack,
    LongShooter,
    ShortHitter,
    Scorer,
    SuperCursedEnergyAttack_01,
    SuperCursedEnergyAttack_02,
    SuperCursedEnergyAttack_03,
    SuperCursedEnergyAttack_04,
    SuperCursedEnergyAttack_05,
    SuperCursedEnergyAttack_06,
    SuperCursedEnergyAttack_07,
    SuperCursedEnergyAttack_08,
    SuperCursedEnergyAttack_09,
    SuperCursedEnergyAttack_10,
    SuperCursedEnergyAttack_11,
    SuperCursedEnergyAttack_12,
    SuperCursedEnergyAttack_13,
    SuperCursedEnergyAttack_14,
    SuperCursedEnergyAttack_15,
    SuperCursedEnergyAttack_16,
    NoRecovery,
    BindingVowsWelcome,
    CursedSpiritsHunter,
    BossKiller,
    AnnihilationKing,
    SuperCursedEnergyAttack_17,
    SuperCursedEnergyAttack_18,
    SuperCursedEnergyAttack_19,
    SuperCursedEnergyAttack_20,
    SuperCursedEnergyAttack_21,
    SuperCursedEnergyAttack_22,
    SuperCursedEnergyAttack_23,
    SuperCursedEnergyAttack_24,
    SuperCursedEnergyAttack_25,
    SuperCursedEnergyAttack_26,
    SuperCursedEnergyAttack_27,
    Invalid = 255,
};

