#pragma once
#include "CoreMinimal.h"
#include "EGameChatLabel.generated.h"

UENUM(BlueprintType)
enum class EGameChatLabel : uint8 {
    None,
    Greeting_1,
    Greeting_2,
    Praise_1,
    Praise_2,
    Follow,
    Apology,
    Gratitude_1,
    Gratitude_2,
    GoodBye,
    ThankYouForYourHardWork,
    RogerThat,
    Rejection,
    Encouragement,
    Pinch,
    ComeForward,
    ComeForward_Out,
    GoDown,
    GoDown_Out,
    Note,
    AimAtTheTarget,
    AimForAJointAttack,
    AimForAJointAttack_Out,
    AimForASuperCursedEnergyAttack,
    AimForASuperCursedEnergyAttack_Out,
    FightCloseBy,
    FightCloseBy_Out,
    FightAway,
    FightAway_Out,
    LetMeTakeCareOfThat,
    LetMeTakeCareOfThat_Out,
    LetsWorkTogether,
    LetsWorkTogether_Out,
    LevelReport_Low,
    LevelReport_Medium,
    LevelReport_High,
    Provocation_1,
    Provocation_2,
    Respect_1,
    Respect_2,
    Unique_1,
    Unique_2,
    Unique_3,
    Unique_4,
    Unique_5,
    Unique_6,
    Unique_7,
    Unique_8,
    Unique_9,
    Unique_10,
    Ready,
    UnderstoodOkay,
    EndsWith,
    WaitAMinute,
    Change,
    ItWasAGoodMatch,
    Exit,
    LetsAttack,
    FightCarefully,
    Invalid = 255,
};

