#pragma once
#include "CoreMinimal.h"
#include "EGamePhase.generated.h"

UENUM(BlueprintType)
enum class EGamePhase : uint8 {
    Boot,
    DebugBoot,
    Startup,
    Logo,
    LicenseAgreement,
    Title,
    MainMenuTop,
    MainMenuStory,
    MainMenuPvP,
    MainMenuPvE,
    MainMenuFreeBattle,
    MainMenuLobby,
    MainMenuCollection,
    MainMenuShop,
    MainMenuArcade,
    StoryCharacterSelect,
    StoryDemoPreBattle,
    StoryDemoPostBattle,
    StoryDemoShortStory,
    StoryDemoCollection,
    BattleTest,
    BattleAgingOnline,
    BattleDemo,
    BattleStory,
    BattleFree,
    BattlePvP,
    BattlePvESolo,
    BattlePvETag,
    BattleReplay,
    BattleVisualLobby,
    BattleArcade,
    IntervalPvE,
    IntervalArcade,
    Credits,
    LevelSequencer,
    Script,
    StoryDemoTest,
    WidgetTest,
    SystemTest,
    LevelSequenceRecording,
    Invalid = 255,
};

