#pragma once
#include "CoreMinimal.h"
#include "EGameUserRecord.generated.h"

UENUM(BlueprintType)
enum class EGameUserRecord : uint8 {
    Min,
    DashCount = Min,
    JustGuardCount,
    GuardBreakCount,
    CursedEnergyLevelupCount,
    CursedEnergyAttackCount,
    CursedEnergyAttackLevelMaxCount,
    LinkComboCount,
    ShortRangeAttackCount,
    LongRangeAttackCount,
    DebuffCount,
    SuperCursedEnergyAttackCount,
    SuperCursedEnergyAttackFinishCount,
    DomainExpansionCount,
    SpecialTagComboCount,
    SpecialTagComboFinishCount,
    AttackComboCount,
    WinWithJujutsuSorcerersCount,
    WinWithoutJujutsuSorcerersCount,
    PerfectWinCount,
    PvPRankMatchWinCount,
    PvPRankMatchLoseCount,
    PvPRankMatchBattleCount,
    PvPRankPointMax,
    PvPEvaluationACount,
    PvPEvaluationSCount,
    PvPBattleCount,
    PvPTotalScore,
    PvPTotalWinCount,
    PvESoloTaskClearCount,
    PvETagTaskClearCount,
    PvEBindingVowsEquipmentCount,
    PvEHealPointUseCount,
    PvEScoreMax,
    PvENormalModeClearCount,
    PvENormalModeTotalScore,
    PvESurvivalModeClearCount,
    PvESurvivalModeTotalScore,
    PvEEvaluationACount,
    PvEEvaluationSCount,
    PvETotalCount,
    FriendBattleCount,
    TotalBattleCount,
    TotalMoney,
    ArcadeClearCount,
    PvEExtraMissionCount,
    PvEExtraMissionClearCount,
    Reserve_04,
    Reserve_05,
    Reserve_06,
    Reserve_07,
    Reserve_08,
    Reserve_09,
    Reserve_10,
    Reserve_11,
    Reserve_12,
    Reserve_13,
    Reserve_14,
    Reserve_15,
    Reserve_16,
    Max = Reserve_16,
    Num,
};

