#pragma once
#include "CoreMinimal.h"
#include "EGameShikigamiActionType.generated.h"

UENUM(BlueprintType)
enum class EGameShikigamiActionType : uint8 {
    Default,
    Idle,
    Run,
    Dash,
    DashBegin,
    DashEnd,
    DashAir,
    DashAirBegin,
    DashAirEnd,
    Jump,
    JumpBegin,
    RunJump,
    RunJumpBegin,
    DashJump,
    DashJumpBegin,
    JumpAir,
    JumpAirBegin,
    RunJumpAir,
    RunJumpAirBegin,
    JumpTop,
    Fall,
    Landing,
    Attack_1,
    Attack_2,
    Attack_3,
    Attack_4,
    Attack_5,
    Attack_6,
    Attack_7,
    Attack_8,
    Attack_9,
    Attack_10,
    Damage,
    Down,
    DownEnd,
    BlowGroundRestraint,
    JugonStunReceive,
    CoercionReceive,
    UnlimitedVoidReceive,
    SimpleDomainCounterStunReceive,
    SummonDefault,
    Summon,
    SummonIdle,
    ReleaseDefault,
    Release,
    ReleaseDown,
    Max = ReleaseDown,
    Num,
    Invalid = 255,
};

