#pragma once
#include "CoreMinimal.h"
#include "EGameCharacterBehavior_AI.generated.h"

UENUM(BlueprintType)
enum class EGameCharacterBehavior_AI : uint8 {
    Idle,
    Run,
    Dash,
    Jump,
    JumpAir,
    DashJump,
    Guard,
    Step,
    BreakFall,
    JustGuard,
    Avoid,
    NormalAttack_1,
    NormalAttack_1_1,
    NormalAttack_2,
    NormalAttack_2_1,
    NormalAttack_3,
    NormalAttack_3_1,
    CursedEnergyAttack_1,
    CursedEnergyAttack_1_1,
    CursedEnergyAttack_2,
    CursedEnergyAttack_2_1,
    SuperCursedEnergyAttack,
    ExtraAttack,
    ChangeTarget,
    Random,
    Append,
    Chase = Append,
    Escape,
    RandomMove,
    Sandbag,
    TagCombo,
    StepDodge,
    Controller2P,
    TrainingNum,
    TutorialAttack_1 = Append,
    TutorialAttack_2 = Escape,
    TutorialGuard_1 = RandomMove,
    TutorialNum = Sandbag,
    Training_Top = Append,
    Training_Bottom = Controller2P,
    Tutorial_Top = Append,
    Tutorial_Bottom = RandomMove,
    Invalid = 255,
};

