#pragma once
#include "CoreMinimal.h"
#include "EGameInputKey.generated.h"

UENUM(BlueprintType)
enum class EGameInputKey : uint8 {
    Min,
    Decision = Min,
    Cancel,
    Dash,
    Jump,
    Guard,
    NormalAttack_1,
    NormalAttack_2,
    NormalAttack_3,
    CursedEnergyAttack_1,
    CursedEnergyAttack_2,
    TargetChangeLeft,
    TargetChangeRight,
    TargetChangeNear,
    Option,
    Select,
    OperationTargetChange,
    CameraModeChange,
    WidgetUp,
    WidgetDown,
    WidgetLeft,
    WidgetRight,
    PopupMenu_1,
    PopupMenu_2,
    NextMenu,
    PrevMenu,
    ChatUp,
    ChatDown,
    ChatLeft,
    ChatRight,
    PlayableCharacterChangeLeft,
    PlayableCharacterChangeRight,
    ScriptSkip,
    ScriptAuto,
    MoveUp,
    MoveDown,
    MoveLeft,
    MoveRight,
    CameraUp,
    CameraDown,
    CameraLeft,
    CameraRight,
    BattlePause,
    Pagination,
    Filter,
    PrevContent,
    NextContent,
    WidgetDispSwitch,
    WidgetDispSwitchMenu,
    OnlineSequencerSkip,
    MainMenuThemeOpen,
    Max = NextContent,
    Num = WidgetDispSwitch,
    Invalid = 255,
};

